# Generated by Django 4.2.27 on 2026-01-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='gifts/', verbose_name='Imagem')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('category', models.CharField(choices=[('cozinha', 'Cozinha'), ('quarto', 'Quarto'), ('banheiro', 'Banheiro'), ('sala', 'Sala'), ('decoracao', 'Decoração'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria')),
                ('total_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade Total')),
                ('purchased_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade Comprada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Presente',
                'verbose_name_plural': 'Presentes',
                'ordering': ['name'],
            },
        ),
    ]
