# Generated by Django 4.2.27 on 2026-01-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=100, verbose_name='Nome do Noivo')),
                ('bride_name', models.CharField(max_length=100, verbose_name='Nome da Noiva')),
                ('wedding_date', models.DateTimeField(verbose_name='Data do Casamento')),
                ('ceremony_location_name', models.CharField(max_length=200, verbose_name='Nome do Local')),
                ('ceremony_location_address', models.TextField(verbose_name='Endereço Completo')),
                ('ceremony_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('ceremony_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('party_location_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do Local da Festa')),
                ('party_location_address', models.TextField(blank=True, verbose_name='Endereço da Festa')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Imagem Hero')),
                ('thank_you_message', models.TextField(default='Obrigado por fazer parte do nosso dia especial!', verbose_name='Mensagem de Agradecimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Evento',
                'verbose_name_plural': 'Configurações do Evento',
            },
        ),
    ]
