# Generated by Django 4.2.9 on 2026-01-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_noivo', models.CharField(max_length=100, verbose_name='Nome do Noivo')),
                ('nome_noiva', models.CharField(max_length=100, verbose_name='Nome da Noiva')),
                ('data_casamento', models.DateTimeField(verbose_name='Data e Hora do Casamento')),
                ('local_nome', models.CharField(max_length=200, verbose_name='Nome do Local')),
                ('local_endereco', models.TextField(verbose_name='Endereço Completo')),
                ('local_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('local_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('local_maps_url', models.URLField(blank=True, verbose_name='Link Google Maps')),
                ('local_waze_url', models.URLField(blank=True, verbose_name='Link Waze')),
                ('mensagem_agradecimento', models.TextField(default='Obrigado por nos presentear! ❤️', verbose_name='Mensagem de Agradecimento')),
            ],
            options={
                'verbose_name': 'Configuração do Evento',
                'verbose_name_plural': 'Configurações do Evento',
            },
        ),
    ]
