# Generated by Django 4.2.9 on 2026-01-22 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('token_convite', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token do Convite')),
                ('confirmou_presenca', models.BooleanField(blank=True, null=True, verbose_name='Confirmou Presença')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Confirmação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Convidado',
                'verbose_name_plural': 'Convidados',
                'ordering': ['nome'],
            },
        ),
    ]
