# Generated by Django 4.2.9 on 2026-01-22 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comprador', models.CharField(max_length=200, verbose_name='Nome do Comprador')),
                ('email_comprador', models.EmailField(max_length=254, verbose_name='E-mail do Comprador')),
                ('telefone_comprador', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Comprador')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('asaas_payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Pagamento Asaas')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('received', 'Recebido'), ('overdue', 'Vencido')], default='pending', max_length=20, verbose_name='Status')),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito'), ('BOLETO', 'Boleto')], max_length=20, verbose_name='Método de Pagamento')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code PIX')),
                ('qr_code_image', models.URLField(blank=True, verbose_name='Imagem QR Code')),
                ('link_pagamento', models.URLField(verbose_name='Link de Pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('presente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifts.gift', verbose_name='Presente')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
