# Generated by Django 4.2.27 on 2026-01-22 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Nome do Comprador')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('buyer_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito')], max_length=20, verbose_name='Método de Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('received', 'Recebido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem para os Noivos')),
                ('asaas_payment_id', models.CharField(blank=True, max_length=100, verbose_name='Asaas Payment ID')),
                ('asaas_invoice_url', models.URLField(blank=True, verbose_name='URL da Fatura')),
                ('pix_qr_code', models.TextField(blank=True, verbose_name='PIX QR Code')),
                ('pix_copy_paste', models.TextField(blank=True, verbose_name='PIX Copia e Cola')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifts.gift', verbose_name='Presente')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
